name: Env var test

on:
  push:
    branches: [ master ]

env:
  ee: dev
  composed: ee

jobs:

  ee:
    runs-on: ubuntu-latest
    env:
      value: test-${{ env.ee }}
    steps:
    - run: "echo Value: $value - Environment: $environment"