name: Env var test

on:
  push:
    branches: [ master ]

env:
  environment: dev
  composed: ${{ env.environment }}

jobs:

  environment:
    runs-on: ubuntu-latest
    env:
      value: test-${{ env.environment }}
    steps:
    - run: echo $value