name: Env var test

on:
  push:
    branches: [ master ]

env:
  ee: dev
  composed: ee_${{ env.ee }}

jobs:

  ee:
    runs-on: ubuntu-latest
    env:
      value: testing_${{ env.ee }}
    steps:
    - run: "echo Value: $value - Environment: $environment"